In [29]:
import pandas as pd
kp=pd.read_csv("C:/Users/Kailash J Choudhary/Desktop/powerbi_industry_sales_loss_analysis_project/messy_sales_orders_5060_rows_csv.csv")
product=pd.read_csv("C:/Users/Kailash J Choudhary/Desktop/powerbi_industry_sales_loss_analysis_project/products_lookup_csv.csv")

In [16]:
print(kp.isnull().sum())

Order_ID               0
Order_Date             0
Customer_ID            0
Customer_Name          0
Segment                0
Region                 0
State                  0
City                   0
Product_ID             0
Product_Category       0
Product_Name           0
Quantity               0
Unit_Price             0
Discount_Percent      40
Unit_Cost             47
Shipping_Cost          0
Marketing_Cost         0
Payment_Mode           0
Sales_Channel          0
Order_Status           0
Salesperson            0
Production_City        0
Customer_Rating      868
Return_Reason       4718
dtype: int64

In [28]:
print(kp.duplicated().sum())

0

In [29]:
#count and remove duplicates values 
print("Before:", kp.duplicated().sum())
kp = kp.drop_duplicates()
print("After:", kp.duplicated().sum())
print(kp.shape)

Before: 0
After: 0
(5000, 24)

In [27]:
#remove extra space and set city title
kp["City"]=kp["City"].str.title().str.strip()
print(kp.head())

    Order_ID Order_Date Customer_ID Customer_Name    Segment Region  \
0  ORD000001 2024-11-23       C0184  Customer 184   Consumer  North
1  ORD000002 2025-08-28       C0089   Customer 89  Corporate  North
2  ORD000003 2024-03-02       C0344  Customer 344   Consumer   East
3  ORD000004 2024-11-30       C0077   Customer 77   Consumer   East
4  ORD000005 2025-09-09       C0463  Customer 463   Consumer  North

           State     City Product_ID Product_Category  ... Unit_Cost  \
0      Rajasthan   Jaipur       P002      Electronics  ...  20287.21
1  Uttar Pradesh  Lucknow       P015       Appliances  ...   2578.90
2          Bihar    Patna       P001      Electronics  ...  38650.52
3          Bihar    Patna       P002      Electronics  ...  20260.04
4      Rajasthan   Jaipur       P010  Office Supplies  ...    121.30

   Shipping_Cost  Marketing_Cost  Payment_Mode  Sales_Channel  Order_Status  \
0            300         1178.35   Credit Card         Online     Delivered
1            200          131.69   Credit Card         Online    In Transit
2             80         8240.79        Wallet    Distributor     Delivered
3            200          637.20   Credit Card         Online      Returned
4            200           27.24           COD         Online     Delivered

   Salesperson Production_City Customer_Rating Return_Reason
0       Farhan            Pune             1.0           NaN
1       Farhan            Pune             1.0           NaN
2     Priyanka       Hyderabad             NaN           NaN
3        Imran       Ahmedabad             4.0   Price Issue
4          Jay       Bengaluru             3.0           NaN

[5 rows x 24 columns]
0       False
1       False
2       False
3       False
4       False
        ...
5055    False
5056    False
5057    False
5058    False
5059    False
Name: City, Length: 5060, dtype: bool

In [5]:
print(kp["Order_Date"].head(10))
print(kp["Order_Date"].isnull().sum())
kp["Order_Date"]=pd.to_datetime(
    kp["Order_Date"],
    errors="coerce",
    dayfirst=True
)

0   2024-11-23
1   2025-08-28
2   2024-03-02
3   2024-11-30
4   2025-09-09
5   2024-08-15
6   2024-01-31
7   2025-10-07
8   2024-12-06
9   2025-05-19
Name: Order_Date, dtype: datetime64[us]
143

In [6]:
1. Remove duplicate rows
2. Fix text format
3. Fix dates
4. Replace Discount null with 0
5. Fill Unit_Cost null from products_lookup
6. Handle Customer_Rating null
7. Remove/flag negative Quantity
8. Fix negative Marketing_Cost
9. Check returned orders without reason

SyntaxError: invalid syntax (679012094.py, line 1)

In [32]:
print(kp["Discount_Percent"].head())
kp.loc[
    kp["Discount_Percent"].isnull(),
    ["Order_ID", "Discount_Percent"]
]
kp.loc[
        kp["City"]=="jaipur",
        ["Order_ID","City"]]

0     5.0
1     5.0
2    35.0
3    12.0
4    10.0
Name: Discount_Percent, dtype: float64

Empty DataFrame
Columns: [Order_ID, City]
Index: []

In [35]:
kp.loc[
        kp["City"]=="Jaipur",
        ["Order_ID","City"]]

       Order_ID    City
0     ORD000001  Jaipur
4     ORD000005  Jaipur
36    ORD000037  Jaipur
89    ORD000090  Jaipur
99    ORD000100  Jaipur
...         ...     ...
4964  ORD004965  Jaipur
4983  ORD004984  Jaipur
4988  ORD004989  Jaipur
4989  ORD004990  Jaipur
4992  ORD004993  Jaipur

[234 rows x 2 columns]

In [40]:
print(kp["Discount_Percent"].isnull().sum())
kp.head()
kp["Discount_Percent"]=kp["Discount_Percent"].fillna(0)

0

In [53]:
kp["Customer_Rating"].isnull().sum()
avg_rating=kp["Customer_Rating"].mean()
kp["Customer_Rating"]=kp["Customer_Rating"].fillna(avg_rating)
kp["Customer_Rating"].isnull().sum()
kp.loc[
        kp["Customer_Rating"]<0
        ]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Segment, Region, State, City, Product_ID, Product_Category, Product_Name, Quantity, Unit_Price, Discount_Percent, Unit_Cost, Shipping_Cost, Marketing_Cost, Payment_Mode, Sales_Channel, Order_Status, Salesperson, Production_City, Customer_Rating, Return_Reason]
Index: []

[0 rows x 24 columns]

In [12]:
# convert all  negative Quantity in to positive quantity
kp.loc[
    kp["Quantity"] < 0,
    ["Order_ID", "Product_Name", "Quantity", "Order_Status"]
]
kp["Quantity"] = kp["Quantity"] .abs()
kp.loc[
    kp["Quantity"] < 0,
    ["Order_ID", "Product_Name", "Quantity", "Order_Status"]
]

Empty DataFrame
Columns: [Order_ID, Product_Name, Quantity, Order_Status]
Index: []

In [ ]:
kp=kp.merge(
        product[["Product_ID","Base_Unit_Price"]],
        on="Product_ID",
        how="left"
)

In [ ]:
kp["Unit_Cost"]=kp["Unit_Cost"].fillna(kp["Base_Unit_Price"])
kp=kp.drop(columns=["Base_Unit_Price"])

In [55]:
print(kp["Unit_Cost"].isnull().sum())

0

In [63]:
#Fix negative Marketing_Cost
kp.loc[
    (kp["Marketing_Cost"]<0).sum(),
      ["Marketing_Cost"]
    ]
kp["Marketing_Cost"]=kp["Marketing_Cost"].abs()

In [68]:
kp.loc[
    kp["Marketing_Cost"]<0,
      ["Marketing_Cost"]
    ]

Empty DataFrame
Columns: [Marketing_Cost]
Index: []

In [75]:
kp.to_csv("C:/Users/Kailash J Choudhary/Desktop/powerbi_industry_sales_loss_analysis_project/cleaned_messy_sales_orders_5060_rows_csv.csv",index="false")